apiVersion: v1
kind: Service
metadata:
  name: my-teams-service
  annotations:
    service.beta.kubernetes.io/linode-loadbalancer-throttle: "4"
  labels:
    app: my-teams
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: my-teams
  sessionAffinity: None